[SDPA-5028] Added data table component.
dpc-sdp/tide_landing_page pull request #136
Opened 2021-03-29 04:43 UTC by MdNadimHossain

2021-03-30 06:55 UTC, anthony-malkoun commented
I'm confused by how you add the actual data to the component?

2021-04-07 07:51 UTC, MdNadimHossain commented on composer.json
> +        "dpc-sdp/tide_core": "dev-feature/SDPA-5028-data-table-component as 2.0.4",
This needs to be revert back once CR is done and tide_core is released.

2021-04-19 04:17 UTC, vincent-gao requested changes
lint~ @MdNadimHossain

2021-04-19 04:43 UTC, vincent-gao approved these changes

2021-04-19 04:44 UTC, merged