[SDPA-5105] Added hook to clear reference node cahce on presave.
dpc-sdp/tide_landing_page pull request #150
Opened 2021-07-22 06:18 UTC by MdNadimHossain

### Jira - 
https://digital-engagement.atlassian.net/browse/SDPA-5105

### Issue -
if the promotion and navigation card has an internal link referenced in it and when the internal link node gets updated, the details does not get updated in the cards where the node is referenced.

### Changes
1. Added a function to query the nodes that are referencing a particual node in the promotion and navigation card.
2. Added node pre-save hook to clear cache for all the parent nodes where the current node is referred.

2021-07-22 13:08 UTC, vincent-gao commented
Hey @MdNadimHossain , 

The function is doing 2 times of queries, which makes it communicating with the database 2 times, it is kind of unnecessary. 
so I suggest two alternative options.
1. use one-time mysql query to get the parent ids, something like below
`
select p.parent_id from paragraphs_item_field_data p left join paragraph__field_paragraph_link l on l.entity_id=p.id where l.bundle in ('navigation_card', 'promotion_card') and l.field_paragraph_link_uri='entity:node/{id}';
`

2. or use `drupal_static` function to maintain a cache tags array you want to invalidate.

2021-07-22 13:09 UTC, vincent-gao requested changes

2021-07-22 13:09 UTC, vincent-gao commented on tide_landing_page.module
> +  try {
please see the comment.

2021-07-22 13:28 UTC, MdNadimHossain commented
> Hey @MdNadimHossain ,
> 
> The function is doing 2 times of queries, which makes it communicating with the database 2 times, it is kind of unnecessary.
> so I suggest two alternative options.
> 
> 1. use one-time mysql query to get the parent ids, something like below
>    `select p.parent_id from paragraphs_item_field_data p left join paragraph__field_paragraph_link l on l.entity_id=p.id where l.bundle in ('navigation_card', 'promotion_card') and l.field_paragraph_link_uri='entity:node/{id}';`
> 2. or use `drupal_static` function to maintain a cache tags array you want to invalidate.

Hmm agree, I like the first approach, should just query once to get the node ids. Thanks for that @vincent-gao 
I will update the query 👍

2021-07-22 13:44 UTC, vincent-gao commented on tide_landing_page.module
> +  try {
hey @MdNadimHossain , IMO, the `try`  is unnecessary. 
as there is no IO operation happening from here, and drupal does these check or exceptions handling for use, especially for using Drupal storage query or `\Drupal::database()`.
in this case, if you want to catch an exception, I personal suggest that you could do this from 
`$result = $query->execute();` line,  the execute statement.

2021-07-22 13:48 UTC, vincent-gao requested changes
sorry, added another comment.

2021-07-26 00:29 UTC, vincent-gao approved these changes
Thanks for the changes @MdNadimHossain

2021-07-28 06:39 UTC, merged