Added basic text enhancer.
dpc-sdp/tide_landing_page pull request #162
Opened 2021-12-03 05:37 UTC by MdNadimHossain

2022-02-03 23:11 UTC, vincent-gao requested changes
@MdNadimHossain , could you please add phpunit tests into it.

2022-02-22 02:23 UTC, MdNadimHossain commented on dev-tools.sh
> +export GH_COMMIT=a93e9347eaedfebe31970929c16d4d8b17daee3b
this needs to be removed once the dev-tools get a release with this changes - https://github.com/dpc-sdp/dev-tools/pull/71

2022-02-22 02:27 UTC, vincent-gao commented
Thanks @MdNadimHossain for the change. LGTM

2022-02-22 02:27 UTC, vincent-gao approved these changes

2022-02-28 05:20 UTC, merged