Feature/sdpa 6050 display two stat grid blocks
dpc-sdp/tide_landing_page pull request #168
Opened 2022-03-28 11:27 UTC by mayurngondhkar

**Jira** : https://digital-engagement.atlassian.net/browse/SDPA-6050

**Changes**
1) When a user adds a statistic grid then by default 2 stat grid blocks should display.

![image](https://user-images.githubusercontent.com/9244829/160388305-773138fe-b60b-4720-abaa-75c303c1419f.png)

2022-03-28 12:57 UTC, mayurngondhkar commented
Branch is based of [[SDPA-6057] Fix Statistics Grid Edit incorrect number of grids](https://github.com/dpc-sdp/tide_landing_page/pull/168/commits/fcb03c8060b1deeb77889cfe2780b077b0904500)

Changes to code.

`/ Display a default of 2 statistics-grid blocks
      if(statisticsGridBlockCount === 1) {
        // Hide the first statistics-grid block while the second one loads
        $('.paragraph-type--statistics-grid').find('tr[class*=draggable]').hide()
        // Add another statistic grid block
        $(context).find("input[id*=field-statistic-block-add-more-add-more-button-statistic-block]").click();
      }`

2022-03-28 21:50 UTC, anthony-malkoun requested changes

2022-03-28 21:50 UTC, anthony-malkoun commented on js/statistics_grid.js
> +  Drupal.behaviors.hideParagraphs = {
Maybe rename this to describe what it's doing. It's not hiding paragraphs but more about making sure there are at least 2 statistic grid blocks.

2022-03-28 21:56 UTC, anthony-malkoun commented
Just doing some light testing on this, I think you might also need to look at removal when it is down to the last 2 items. It probably should just remove both?

2022-03-28 22:09 UTC, anthony-malkoun commented
I also think maybe the `Remove` button on the first block should be removed? @mayurngondhkar can you talk to the team about getting a little bit of light UX thought on this?

2022-03-28 23:27 UTC, vincent-gao commented
@mayurngondhkar 
I think we don't want to include any JS code in our modules. as it is hard to maintain, and sometimes it doesn't work when our upstream modules get updated. we should just use PHP if it is possible.

cc @anthony-malkoun

2022-03-28 23:29 UTC, vincent-gao requested changes
you should use PHP(Drupal) way instead of JS.

2022-03-28 23:35 UTC, vincent-gao commented
@mayurngondhkar 
some modules/solutions that may be relevant 
https://www.drupal.org/project/default_paragraphs
https://www.drupal.org/project/paragraphs_browser/issues/3096918

cc @anthony-malkoun

2022-05-18 05:16 UTC, mayurngondhkar commented
New SD applied in PR https://github.com/dpc-sdp/content-reference-sdp-vic-gov-au/pull/80

This PR is no longer required.

2022-05-18 05:16 UTC, closed without merging