deleted style field
dpc-sdp/tide_landing_page pull request #230
Opened 2024-07-29 04:44 UTC by yeniatencio

2024-08-20 01:31 UTC, vincent-gao requested changes
hey @yeniatencio 
There are a couple of dependency concerns:
1. all of tide modules they don't have dependency with drush, so I think you don't want to introduce drush dependency here.
2. https://github.com/dpc-sdp/tide_landing_page/pull/230/files#diff-7e6f6816fd76f77a0b74239e31ba4e5b1e332854d8e55ceae374edfe98dfe08bR98 could potentially overwrite configurations unintentionally for some projects, since the landing_page is used across all sites.

2024-08-26 02:36 UTC, yeniatencio commented
> hey @yeniatencio There are a couple of dependency concerns:
> 
> 1. all of tide modules they don't have dependency with drush, so I think you don't want to introduce drush dependency here.
> 2. https://github.com/dpc-sdp/tide_landing_page/pull/230/files#diff-7e6f6816fd76f77a0b74239e31ba4e5b1e332854d8e55ceae374edfe98dfe08bR98 could potentially overwrite configurations unintentionally for some projects, since the landing_page is used across all sites.

Hey @vincent-gao , regarding to your feedback:
1. I need a dependency with drush. If that's not the correct place to add it then please point me where it should be added instead. 
2. Please be more specific and suggest what is the best approach because the ticket is requesting to remove a field.

2024-08-27 03:13 UTC, MdNadimHossain approved these changes
Looks good to me, but please get a 2nd opinion from @vincent-gao

2024-08-27 03:28 UTC, vincent-gao approved these changes

2024-08-27 07:02 UTC, merged